workflows:
  capacitor-android:
    name: Build Capacitor Android App
    environment:
      node: 16.13.0
    scripts:
      - npm install
      - npx cap add android
      - npx cap sync android
      - cd android
      - bash gradlew assembleDebug    # ✅ 핵심 변경!
    artifacts:
      - android/app/build/outputs/**/*.apk
