workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
