workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk