workflows:
  capacitor-android:
    name: Build Capacitor Android App
    environment:
      node: 16.13.0
    scripts:
      - npm install
      - npx cap add android
      - npx cap sync android
      - chmod +x android/gradlew     # ✅ 실행 권한 부여!
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
