workflows:
  capacitor-android:
    name: Build Capacitor Android App
    environment:
      vars:
        PACKAGE_NAME: "com.example.chessai"
      node: 16.13.0
    scripts:
      - npm install
      - npx cap add android       # ← 여기가 추가된 핵심 줄!
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
